//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp._sys {


    public partial class GrowattAPISetting {

        protected global::System.Web.UI.WebControls.TextBox txtUrl;

        protected global::System.Web.UI.WebControls.TextBox txtAccount;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.TextBox txtToken;

        protected global::System.Web.UI.WebControls.TextBox txtDate;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.Button btnReload;
    }
}
